/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TherapieCoupleAmiensRouteImport } from './routes/therapie-couple-amiens'
import { Route as TarifsPsyAmiensRouteImport } from './routes/tarifs-psy-amiens'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as HypnoseAmiensRouteImport } from './routes/hypnose-amiens'
import { Route as EmdrAmiensRouteImport } from './routes/emdr-amiens'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as BurnOutAmiensRouteImport } from './routes/burn-out-amiens'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ApprochesRouteImport } from './routes/approches'
import { Route as AnxieteDepressionAmiensRouteImport } from './routes/anxiete-depression-amiens'
import { Route as AnalyseTransactionnelleAmiensRouteImport } from './routes/analyse-transactionnelle-amiens'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'

const TherapieCoupleAmiensRoute = TherapieCoupleAmiensRouteImport.update({
  id: '/therapie-couple-amiens',
  path: '/therapie-couple-amiens',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsPsyAmiensRoute = TarifsPsyAmiensRouteImport.update({
  id: '/tarifs-psy-amiens',
  path: '/tarifs-psy-amiens',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const HypnoseAmiensRoute = HypnoseAmiensRouteImport.update({
  id: '/hypnose-amiens',
  path: '/hypnose-amiens',
  getParentRoute: () => rootRouteImport,
} as any)
const EmdrAmiensRoute = EmdrAmiensRouteImport.update({
  id: '/emdr-amiens',
  path: '/emdr-amiens',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const BurnOutAmiensRoute = BurnOutAmiensRouteImport.update({
  id: '/burn-out-amiens',
  path: '/burn-out-amiens',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprochesRoute = ApprochesRouteImport.update({
  id: '/approches',
  path: '/approches',
  getParentRoute: () => rootRouteImport,
} as any)
const AnxieteDepressionAmiensRoute = AnxieteDepressionAmiensRouteImport.update({
  id: '/anxiete-depression-amiens',
  path: '/anxiete-depression-amiens',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyseTransactionnelleAmiensRoute =
  AnalyseTransactionnelleAmiensRouteImport.update({
    id: '/analyse-transactionnelle-amiens',
    path: '/analyse-transactionnelle-amiens',
    getParentRoute: () => rootRouteImport,
  } as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/analyse-transactionnelle-amiens': typeof AnalyseTransactionnelleAmiensRoute
  '/anxiete-depression-amiens': typeof AnxieteDepressionAmiensRoute
  '/approches': typeof ApprochesRoute
  '/blog': typeof BlogRoute
  '/burn-out-amiens': typeof BurnOutAmiensRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/emdr-amiens': typeof EmdrAmiensRoute
  '/hypnose-amiens': typeof HypnoseAmiensRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/tarifs-psy-amiens': typeof TarifsPsyAmiensRoute
  '/therapie-couple-amiens': typeof TherapieCoupleAmiensRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/analyse-transactionnelle-amiens': typeof AnalyseTransactionnelleAmiensRoute
  '/anxiete-depression-amiens': typeof AnxieteDepressionAmiensRoute
  '/approches': typeof ApprochesRoute
  '/blog': typeof BlogRoute
  '/burn-out-amiens': typeof BurnOutAmiensRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/emdr-amiens': typeof EmdrAmiensRoute
  '/hypnose-amiens': typeof HypnoseAmiensRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/tarifs-psy-amiens': typeof TarifsPsyAmiensRoute
  '/therapie-couple-amiens': typeof TherapieCoupleAmiensRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/analyse-transactionnelle-amiens': typeof AnalyseTransactionnelleAmiensRoute
  '/anxiete-depression-amiens': typeof AnxieteDepressionAmiensRoute
  '/approches': typeof ApprochesRoute
  '/blog': typeof BlogRoute
  '/burn-out-amiens': typeof BurnOutAmiensRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/emdr-amiens': typeof EmdrAmiensRoute
  '/hypnose-amiens': typeof HypnoseAmiensRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/tarifs-psy-amiens': typeof TarifsPsyAmiensRoute
  '/therapie-couple-amiens': typeof TherapieCoupleAmiensRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/analyse-transactionnelle-amiens'
    | '/anxiete-depression-amiens'
    | '/approches'
    | '/blog'
    | '/burn-out-amiens'
    | '/confidentialite'
    | '/contact'
    | '/emdr-amiens'
    | '/hypnose-amiens'
    | '/mentions-legales'
    | '/tarifs-psy-amiens'
    | '/therapie-couple-amiens'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/analyse-transactionnelle-amiens'
    | '/anxiete-depression-amiens'
    | '/approches'
    | '/blog'
    | '/burn-out-amiens'
    | '/confidentialite'
    | '/contact'
    | '/emdr-amiens'
    | '/hypnose-amiens'
    | '/mentions-legales'
    | '/tarifs-psy-amiens'
    | '/therapie-couple-amiens'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/analyse-transactionnelle-amiens'
    | '/anxiete-depression-amiens'
    | '/approches'
    | '/blog'
    | '/burn-out-amiens'
    | '/confidentialite'
    | '/contact'
    | '/emdr-amiens'
    | '/hypnose-amiens'
    | '/mentions-legales'
    | '/tarifs-psy-amiens'
    | '/therapie-couple-amiens'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AnalyseTransactionnelleAmiensRoute: typeof AnalyseTransactionnelleAmiensRoute
  AnxieteDepressionAmiensRoute: typeof AnxieteDepressionAmiensRoute
  ApprochesRoute: typeof ApprochesRoute
  BlogRoute: typeof BlogRoute
  BurnOutAmiensRoute: typeof BurnOutAmiensRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  EmdrAmiensRoute: typeof EmdrAmiensRoute
  HypnoseAmiensRoute: typeof HypnoseAmiensRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  TarifsPsyAmiensRoute: typeof TarifsPsyAmiensRoute
  TherapieCoupleAmiensRoute: typeof TherapieCoupleAmiensRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/therapie-couple-amiens': {
      id: '/therapie-couple-amiens'
      path: '/therapie-couple-amiens'
      fullPath: '/therapie-couple-amiens'
      preLoaderRoute: typeof TherapieCoupleAmiensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs-psy-amiens': {
      id: '/tarifs-psy-amiens'
      path: '/tarifs-psy-amiens'
      fullPath: '/tarifs-psy-amiens'
      preLoaderRoute: typeof TarifsPsyAmiensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hypnose-amiens': {
      id: '/hypnose-amiens'
      path: '/hypnose-amiens'
      fullPath: '/hypnose-amiens'
      preLoaderRoute: typeof HypnoseAmiensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emdr-amiens': {
      id: '/emdr-amiens'
      path: '/emdr-amiens'
      fullPath: '/emdr-amiens'
      preLoaderRoute: typeof EmdrAmiensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/burn-out-amiens': {
      id: '/burn-out-amiens'
      path: '/burn-out-amiens'
      fullPath: '/burn-out-amiens'
      preLoaderRoute: typeof BurnOutAmiensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approches': {
      id: '/approches'
      path: '/approches'
      fullPath: '/approches'
      preLoaderRoute: typeof ApprochesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anxiete-depression-amiens': {
      id: '/anxiete-depression-amiens'
      path: '/anxiete-depression-amiens'
      fullPath: '/anxiete-depression-amiens'
      preLoaderRoute: typeof AnxieteDepressionAmiensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyse-transactionnelle-amiens': {
      id: '/analyse-transactionnelle-amiens'
      path: '/analyse-transactionnelle-amiens'
      fullPath: '/analyse-transactionnelle-amiens'
      preLoaderRoute: typeof AnalyseTransactionnelleAmiensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AnalyseTransactionnelleAmiensRoute: AnalyseTransactionnelleAmiensRoute,
  AnxieteDepressionAmiensRoute: AnxieteDepressionAmiensRoute,
  ApprochesRoute: ApprochesRoute,
  BlogRoute: BlogRoute,
  BurnOutAmiensRoute: BurnOutAmiensRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  EmdrAmiensRoute: EmdrAmiensRoute,
  HypnoseAmiensRoute: HypnoseAmiensRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  TarifsPsyAmiensRoute: TarifsPsyAmiensRoute,
  TherapieCoupleAmiensRoute: TherapieCoupleAmiensRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
